server:
  port: 8081
  compression:
    enabled: true
spring:
  application:
    name: product-service
  cache:
    redis:
      time-to-live: 259200000
  redis:
    host: 39.96.38.111
    port: 6379
    database: 0
    password:
    timeout: 100000
    jedis:
      pool:
        max-active: 1024
        max-wait: -1
        max-idle: 200
        min-idle: 5
        enabled: true
eureka:
  instance:
    hostname: product-service
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:1234@localhost:9090/eureka/,http://root:1234@localhost:9091/eureka/
feign:
  httpclient:
    enabled: true

#-------------------------日志配置-------------------------
logging:
  config: classpath:config/logback.xml
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: debug
logging.level.org.apache.http: info