server:
  port: 9090
spring:
  application:
    name: server-master
  security:
    user:
      name: root
      password: 1234
eureka:
  instance:
    hostname: server-master
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:1234@localhost:9091/eureka/
    healthcheck:
      enabled: true
info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    test: test
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

