server:
  port: 8085
  compression:
    enabled: true
  servlet:
    context-path: "/sign/api"
spring:
  application:
    name: sign-service
  cache:
    redis:
      time-to-live: 259200000
  datasource:
    url: jdbc:mysql://39.96.38.111:3306/jan_test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: root
    password: Rong710821
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      pool-name: HikariCP-Pool
      connection-test-query: SELECT 1
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      read-only: false
  jpa:
    database: MySQL
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  redis:
    host: 39.96.38.111
    port: 6379
    database: 0
    password: Rong710821
    timeout: 100000
    jedis:
      pool:
        max-active: 1024
        max-wait: -1
        max-idle: 200
        min-idle: 5
eureka:
  instance:
    hostname: sign-service
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:1234@localhost:9090/eureka/,http://root:1234@localhost:9091/eureka/

feign:
  httpclient:
    enabled: true
  circuitbreaker:
    enabled: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: sign-group
    send-message-timeout: 3000 # 发送消息超时时间，单位：毫秒。默认3000
    compress-message-body-threshold: 4096 # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
    max-message-size: 4194304 # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
    retry-times-when-send-failed: 2 # 同步发送消息时，失败重试次数。默认为 2 次
    retry-times-when-send-async-failed: 2 # 异步发送消息时，失败重试次数。默认为 2 次。
    retry-next-server: false # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
    #    access-key: # Access Key ，可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md 文档
    #    secret-key: # Secret Key
    enable-msg-trace: true # 是否开启消息轨迹功能。默认为 true 开启。可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/msg_trace/user_guide.md 文档
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义消息轨迹的 Topic 。默认为 RMQ_SYS_TRACE_TOPIC 。

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

#-------------------------????-------------------------
logging:
  config: classpath:logback.xml
  level:
    sql: debug
    web: info
    root: info